Run k8s mgmt local (#552)
* Added documentation for running mgmt node on k8s

* Added documentation for running mgmt node on k8s

* Added documentation for running mgmt node on k8s

* get helm and kubectl installation path

* added ingress controller

* removed node labeling

* removed docs

* set Ingress resource

* used hostNetwork for ingress controller

* removed check for nodeName

* added ingress ingressClassName

* updated k8s ingress routing

* expose OpenSearch API via Ingress

* send graylog gelf input via haproxy

* handled gelf tcp request via nginx ingress

* updated webAPI route

* updated foundationdb fileContent path

* updated foundationdb fileContent path

* removed cluster-file hostpath

* get fdbClusterFileContent via configmap

* get file content from db connection

* add subPath to cluster-file volume

* use hostPath to store fdb config

* use helm complete path

* removed clusterIP None

* fixed opensearch url endpoint

* check file exist /etc/foundationdb/fdb.cluster

* switched to FDB_NETWORKING_MODE host

* switched to FDB_NETWORKING_MODE container

* customize fdb.bash script

* added defaultMode to mounted configmap volume

* enable simplyblock-fdb-server tcp support

* get PUBLIC_IP from env

* removed HaProxy

* removed unused configmaps

* add support for ingress with dns

* removed env PUBLIC_IP

* fixed function call is_ip_address

* fixed fdb volumeMount

* fixed fdb env

* added configmap simplyblock-fdb-entrypoint-script as volume

* added cluster param --mgmt-ip

* store k8s nodename in mgmt fdb record

* create directory /etc/foundationdb if it doesn't exist

* updated fdb volumePath

* removed check for fdb.cluster file

* fixed linter  Remove unused import:

* added nodeselector to ingress controller

* added nodeselector to ingress controller

* make ifname optional during mgmt add

* conditionalize ingress controller chart installation

* removed fdb k8s service manifest

* added json extractor

* separated ingress into api and monitoring

* updated mgmt deploy endpoint

* updated cluster metrics endpoint in prometheus config

diff --git a/simplyblock_core/scripts/charts/templates/app_configmap.yaml b/simplyblock_core/scripts/charts/templates/app_configmap.yaml
--- a/simplyblock_core/scripts/charts/templates/app_configmap.yaml
+++ b/simplyblock_core/scripts/charts/templates/app_configmap.yaml
@@ -11,100 +11,6 @@ data:
   LOG_DELETION_INTERVAL: {{ .Values.log.deletionInterval }}
 
 ---
-apiVersion: v1
-kind: ConfigMap
-metadata:
-  name: simplyblock-haproxy-config
-  namespace: {{ .Release.Namespace }}
-data:
-  haproxy.cfg: |
-    global
-        log          fd@2 local2
-        chroot       /var/lib/haproxy
-        pidfile      /var/run/haproxy.pid
-        maxconn      4000
-        user         haproxy
-        group        haproxy
-        stats socket /var/lib/haproxy/stats expose-fd listeners
-        master-worker
-
-    resolvers kube-dns
-        nameserver dns1 kube-dns.kube-system.svc.cluster.local:53
-        resolve_retries 3
-        timeout resolve 1s
-        timeout retry   1s
-        hold other      10s
-        hold refused    10s
-        hold nx         10s
-        hold timeout    10s
-        hold valid      10s
-        hold obsolete   10s
-
-    defaults
-        timeout connect 10s
-        timeout client 120s
-        timeout server 120s
-        log global
-        mode http
-        option httplog
-
-    backend stat
-        stats enable
-        stats uri /
-        stats refresh 10s
-        stats show-legends
-        stats show-node
-        stats hide-version
-        stats auth admin:admin
-
-    backend wep_api_services
-        balance roundrobin
-        server-template webapi- 3 simplyblock-webappapi.{{ .Release.Namespace }}.svc.cluster.local:5000 check resolvers kube-dns init-addr libc,none
-
-    backend grafana_services
-        balance roundrobin
-        http-request set-path %[path,regsub(^/grafana/?,/)]
-        server-template grafana- 1 simplyblock-grafana.{{ .Release.Namespace }}.svc.cluster.local:3000 check resolvers kube-dns init-addr libc,none
-
-    backend graylog_services
-        balance roundrobin
-        http-request set-path %[path,regsub(^/graylog/?,/)]
-        server-template graylog- 1 simplyblock-graylog.{{ .Release.Namespace }}.svc.cluster.local:9000 check resolvers kube-dns init-addr libc,none
-
-    backend haproxy_services
-        http-request set-path %[path,regsub(^/haproxy/?,/)]
-        stats enable
-        stats uri /
-        stats refresh 10s
-        stats show-legends
-        stats show-node
-
-    backend graylog_input_services
-        mode tcp
-        balance roundrobin
-        server-template graylog_input- 1 simplyblock-graylog.{{ .Release.Namespace }}.svc.cluster.local:12201 check resolvers kube-dns init-addr libc,none
-
-    backend opensearch_services
-        balance roundrobin
-        server-template opensearch- 1 opensearch-cluster-master.{{ .Release.Namespace }}.svc.cluster.local:9200 check resolvers kube-dns init-addr libc,none
-
-    frontend web_api_front
-        bind *:80
-        use_backend grafana_services if { path /grafana } || { path_beg /grafana/ }
-        use_backend graylog_services if { path /graylog } || { path_beg /graylog/ }
-        use_backend haproxy_services if { path /haproxy } || { path_beg /haproxy/ }
-        default_backend wep_api_services
-
-    frontend graylog_input_front
-        bind *:12202
-        mode tcp
-        default_backend graylog_input_services
-
-    frontend opensearch_front
-        bind *:9200
-        default_backend opensearch_services
-
----
 
 apiVersion: v1
 kind: ConfigMap
@@ -149,8 +55,8 @@ data:
     [OUTPUT]
         Name          gelf
         Match         *
-        Host          simplyblock-haproxy
-        Port          12202
+        Host          simplyblock-graylog
+        Port          12201
         Mode          tcp
         Gelf_Short_Message_Key log
 
@@ -170,3 +76,68 @@ data:
         end
         return -1, record
     end
+
+---
+apiVersion: v1
+kind: ConfigMap
+metadata:
+  name: simplyblock-tcp-services
+  namespace: {{ .Release.Namespace }}
+data:
+  "12202": "{{ .Release.Namespace }}/simplyblock-graylog:12201"
+---
+apiVersion: v1
+kind: ConfigMap
+metadata:
+  name: simplyblock-fdb-entrypoint-script
+  namespace: {{ .Release.Namespace }}
+data:
+  fdb.bash: |
+    #!/bin/bash
+
+    function create_cluster_file() {
+        FDB_CLUSTER_FILE=${FDB_CLUSTER_FILE:-/etc/foundationdb/fdb.cluster}
+        mkdir -p "$(dirname $FDB_CLUSTER_FILE)"
+
+        if [[ -n "$FDB_CLUSTER_FILE_CONTENTS" ]]; then
+            echo "$FDB_CLUSTER_FILE_CONTENTS" > "$FDB_CLUSTER_FILE"
+        elif [[ -n $FDB_COORDINATOR ]]; then
+            coordinator_ip=$(dig +short "$FDB_COORDINATOR")
+            if [[ -z "$coordinator_ip" ]]; then
+                echo "Failed to look up coordinator address for $FDB_COORDINATOR" 1>&2
+                exit 1
+            fi
+            coordinator_port=${FDB_COORDINATOR_PORT:-4500}
+            echo "docker:docker@$coordinator_ip:$coordinator_port" > "$FDB_CLUSTER_FILE"
+        else
+            echo "FDB_COORDINATOR environment variable not defined" 1>&2
+            exit 1
+        fi
+    }
+
+    function create_server_environment() {
+        env_file=/var/fdb/.fdbenv
+
+        if [[ "$FDB_NETWORKING_MODE" == "host" ]]; then
+            public_ip=127.0.0.1
+        elif [[ "$FDB_NETWORKING_MODE" == "container" ]]; then
+            public_ip=${PUBLIC_IP:-$(hostname -i | awk '{print $1}')}
+        else
+            echo "Unknown FDB Networking mode \"$FDB_NETWORKING_MODE\"" 1>&2
+            exit 1
+        fi
+
+        echo "export PUBLIC_IP=$public_ip" > $env_file
+        if [[ -z $FDB_COORDINATOR && -z "$FDB_CLUSTER_FILE_CONTENTS" ]]; then
+            FDB_CLUSTER_FILE_CONTENTS="docker:docker@$PUBLIC_IP:$FDB_PORT"
+        fi
+
+        create_cluster_file
+    }
+
+    create_server_environment
+    source /var/fdb/.fdbenv
+    echo "Starting FDB server on $PUBLIC_IP:$FDB_PORT"
+    fdbserver --listen-address 0.0.0.0:"$FDB_PORT" --public-address "$PUBLIC_IP:$FDB_PORT" \
+        --datadir /var/fdb/data --logdir /var/fdb/logs \
+        --locality-zoneid="$(hostname)" --locality-machineid="$(hostname)" --class "$FDB_PROCESS_CLASS"
