E2E-Adding else for k3s uninstall

diff --git a/.github/workflows/e2e-k8s-server-66.yml b/.github/workflows/e2e-k8s-server-66.yml
--- a/.github/workflows/e2e-k8s-server-66.yml
+++ b/.github/workflows/e2e-k8s-server-66.yml
@@ -169,7 +169,7 @@ jobs:
           fi
 
           for node in $K3S_MNODES $STORAGE_PRIVATE_IPS $SEC_STORAGE_PRIVATE_IPS; do
-            ssh -i ~/.ssh/simplyblock-us-east-2.pem  root@${node} "k3s-agent-uninstall.sh"
+            ssh -i ~/.ssh/simplyblock-us-east-2.pem  root@${node} "k3s-agent-uninstall.sh" || echo "[WARNING] K3s-agent-uninstall failed on $node"
           done
           
           for node in $MNODES; do
