E2E-Adding random name in lvol and exiting on first error during multi-iteration

diff --git a/.github/workflows/e2e-docker-server5.yml b/.github/workflows/e2e-docker-server5.yml
--- a/.github/workflows/e2e-docker-server5.yml
+++ b/.github/workflows/e2e-docker-server5.yml
@@ -182,6 +182,11 @@ jobs:
             echo "Iteration $i"
             python3 e2e.py $TESTNAME \
                     --ndcs $NDCS --npcs $NPCS --bs $BS --chunk_bs $CHUNK_BS --run_ha ${{ github.event.inputs.run_ha_test }}
+            
+            if [[ $? -ne 0 ]]; then
+              echo "Test failed in iteration $i. Exiting..."
+              exit 1
+            fi
           done
         env:
           SBCLI_CMD: ${{ env.SBCLI_CMD }}
