Adding k8s github action

diff --git a/.github/workflows/e2e.yaml b/.github/workflows/e2e.yaml
--- a/.github/workflows/e2e.yaml
+++ b/.github/workflows/e2e.yaml
@@ -207,18 +207,26 @@ jobs:
 
       - name: Wait for Storage Nodes to Become Online
         run: |
+          echo "Sleeping for 120 seconds before helm install"
+          sleep 120
           while true; do
             echo "Checking storage node status..."
             
             NODE_STATUS=$(ssh -i "$HOME/.ssh/${{ steps.terraform_outputs.outputs.key_name }}" \
-                    -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no \
-                    -o ProxyCommand="ssh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -i \"$HOME/.ssh/${{ steps.terraform_outputs.outputs.key_name }}\" -W %h:%p ec2-user@${{ steps.terraform_outputs.outputs.bastion_public_ip }}" \
-                    ec2-user@${{ steps.terraform_outputs.outputs.mgmt_private_ip }} \
+              -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no \
+              -o ProxyCommand="ssh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -i \"$HOME/.ssh/${{ steps.terraform_outputs.outputs.key_name }}\" -W %h:%p ec2-user@${{ steps.terraform_outputs.outputs.bastion_public_ip }}" \
+              ec2-user@${{ steps.terraform_outputs.outputs.mgmt_private_ip }} \
               "sbcli-dev sn list | grep -Eo 'online|offline'" || echo "SSH command failed")
 
             SSH_EXIT_CODE=$?
             if [ $SSH_EXIT_CODE -ne 0 ]; then
               echo "SSH command failed with exit code $SSH_EXIT_CODE. Retrying..."
+              sleep 30
+              continue
+            fi
+
+            if [ -z "$NODE_STATUS" ]; then
+              echo "No output from sbcli-dev sn list. Retrying..."
               sleep 30
               continue
             fi
@@ -411,16 +419,16 @@ jobs:
 
           curl -X POST -H 'Content-type: application/json' --data "{\"text\":\"${MESSAGE}\"}" $SLACK_WEBHOOK_URL
 
-      - name: Destroy Cluster
-        if: always()
-        run: |
-          cd $GITHUB_WORKSPACE/simplyBlockDeploy
-          terraform destroy --auto-approve
+      # - name: Destroy Cluster
+      #   if: always()
+      #   run: |
+      #     cd $GITHUB_WORKSPACE/simplyBlockDeploy
+      #     terraform destroy --auto-approve
 
-      - name: Cleanup build folder
-        run: |
-          ls -la ./
-          rm -rf ./* || true
-          rm -rf ./.??* || true
-          ls -la ./
-          rm -rf $HOME/.kube
+      # - name: Cleanup build folder
+      #   run: |
+      #     ls -la ./
+      #     rm -rf ./* || true
+      #     rm -rf ./.??* || true
+      #     ls -la ./
+      #     rm -rf $HOME/.kube
