Adding k8s github action

diff --git a/.github/workflows/e2e.yaml b/.github/workflows/e2e.yaml
--- a/.github/workflows/e2e.yaml
+++ b/.github/workflows/e2e.yaml
@@ -205,50 +205,49 @@ jobs:
             --set logicalVolume.snapshot="True" \
             --set image.simplyblock.tag="main"
 
-      - name: Wait for Storage Nodes to Become Online
-        run: |
-          echo "Sleeping for 120 seconds before helm install"
-          sleep 120
-          while true; do
-            echo "Checking storage node status..."
+      # - name: Wait for Storage Nodes to Become Online
+      #   run: |
+      #     echo "Sleeping for 120 seconds before helm install"
+      #     sleep 120
+      #     while true; do
+      #       echo "Checking storage node status..."
             
-            NODE_STATUS=$(ssh -i "$HOME/.ssh/${{ steps.terraform_outputs.outputs.key_name }}" \
-              -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no \
-              -o ProxyCommand="ssh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -i \"$HOME/.ssh/${{ steps.terraform_outputs.outputs.key_name }}\" -W %h:%p ec2-user@${{ steps.terraform_outputs.outputs.bastion_public_ip }}" \
-              ec2-user@${{ steps.terraform_outputs.outputs.mgmt_private_ip }} \
-              "sbcli-dev sn list | grep -Eo 'online|offline'" || echo "SSH command failed")
+      #       NODE_STATUS=$(ssh -i "$HOME/.ssh/${{ steps.terraform_outputs.outputs.key_name }}" \
+      #         -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no \
+      #         -o ProxyCommand="ssh -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -i \"$HOME/.ssh/${{ steps.terraform_outputs.outputs.key_name }}\" -W %h:%p ec2-user@${{ steps.terraform_outputs.outputs.bastion_public_ip }}" \
+      #         ec2-user@${{ steps.terraform_outputs.outputs.mgmt_private_ip }} \
+      #         "sbcli-dev sn list | grep -Eo 'online|offline'" || echo "SSH command failed")
 
-            SSH_EXIT_CODE=$?
-            if [ $SSH_EXIT_CODE -ne 0 ]; then
-              echo "SSH command failed with exit code $SSH_EXIT_CODE. Retrying..."
-              sleep 30
-              continue
-            fi
+      #       SSH_EXIT_CODE=$?
+      #       if [ $SSH_EXIT_CODE -ne 0 ]; then
+      #         echo "SSH command failed with exit code $SSH_EXIT_CODE. Retrying..."
+      #         sleep 30
+      #         continue
+      #       fi
 
-            if [ -z "$NODE_STATUS" ]; then
-              echo "No output from sbcli-dev sn list. Retrying..."
-              sleep 30
-              continue
-            fi
+      #       if [ -z "$NODE_STATUS" ]; then
+      #         echo "No output from sbcli-dev sn list. Retrying..."
+      #         sleep 30
+      #         continue
+      #       fi
 
-            echo "Node Status: $NODE_STATUS"
-            ONLINE_NODES=$(echo "$NODE_STATUS" | grep -c "online")
+      #       echo "Node Status: $NODE_STATUS"
+      #       ONLINE_NODES=$(echo "$NODE_STATUS" | grep -c "online")
             
-            if [ "$ONLINE_NODES" -ge 3 ]; then
-              echo "All 3 storage nodes are online."
-              break
-            else
-              echo "$ONLINE_NODES nodes online. Waiting for more nodes to come online..."
-              sleep 30
-            fi
-          done
-        shell: /usr/bin/bash -e {0}
+      #       if [ "$ONLINE_NODES" -ge 3 ]; then
+      #         echo "All 3 storage nodes are online."
+      #         break
+      #       else
+      #         echo "$ONLINE_NODES nodes online. Waiting for more nodes to come online..."
+      #         sleep 30
+      #       fi
+      #     done
+      #   shell: /usr/bin/bash -e {0}
+      - name: Sleep after Helm Installation
+        run: sleep 300
 
       - name: Activate Cluster
         run: |
-          echo "Sleeping for 30 seconds before cluster activate"
-          sleep 30
-
           ssh -i "$HOME/.ssh/${{ steps.terraform_outputs.outputs.key_name }}" -o StrictHostKeyChecking=no \
             -o ProxyCommand="ssh -o StrictHostKeyChecking=no -i \"$HOME/.ssh/${{ steps.terraform_outputs.outputs.key_name }}\" -W %h:%p ec2-user@${{ steps.terraform_outputs.outputs.bastion_public_ip }}" \
             ec2-user@${{ steps.terraform_outputs.outputs.mgmt_private_ip }} "
