Modifying tests for without ndcs and npcs

diff --git a/.github/workflows/e2e.yaml b/.github/workflows/e2e.yaml
--- a/.github/workflows/e2e.yaml
+++ b/.github/workflows/e2e.yaml
@@ -97,7 +97,10 @@ jobs:
         run: |
           cd $GITHUB_WORKSPACE/simplyBlockDeploy
           terraform workspace select -or-create ghiaction-sbclie2e
-
+      - name: Validate Terraform Configuration
+        run: |
+          cd $GITHUB_WORKSPACE/simplyBlockDeploy
+          terraform validate
       - name: Plan Terraform Changes
         run: |
           cd $GITHUB_WORKSPACE/simplyBlockDeploy
@@ -112,16 +115,26 @@ jobs:
         run: |
           cd $GITHUB_WORKSPACE/simplyBlockDeploy
           terraform apply tfplan
-
+      - name: Get Terraform Outputs
+        id: terraform_outputs
+        run: |
+          cd $GITHUB_WORKSPACE/simplyBlockDeploy
+          output_bastion_public_ip=$(terraform output -raw bastion_public_ip)
+          echo "::set-output name=bastion_public_ip::$output_bastion_public_ip"
+          output_key_name=$(terraform output -raw key_name)
+          echo "::set-output name=key_name::$output_key_name"
       - name: Bootstrap Cluster
         run: |
           cd $GITHUB_WORKSPACE/simplyBlockDeploy
           ./bootstrap-cluster.sh --sbcli-cmd "${{ github.event.inputs.sbcli_cmd }}" \
-            --max-lvol 10 --max-snap 10 --max-prov 900g --number-of-devices 3 \
+            --max-lvol 10 --max-snap 10 --max-prov 900G --number-of-devices 3 \
             --distr-ndcs ${{ github.event.inputs.ndcs }} \
             --distr-npcs ${{ github.event.inputs.npcs }} \
             --distr-bs ${{ github.event.inputs.bs }} \
             --distr-chunk-bs ${{ github.event.inputs.chunk_bs }}
+        id: bootstrap_cluster
+        env:
+          SBCLI_CMD: ${{ github.event.inputs.sbcli_cmd || 'sbcli-dev' }}
 
       - name: Record Test Start Time
         run: echo "TEST_START_TIME=$(date +%s)" >> $GITHUB_ENV
@@ -135,6 +148,16 @@ jobs:
           source myenv/bin/activate
           python3 -m pip install -r requirements.txt
           echo "Running tests in namespace ${{ steps.get-namespace.outputs.namespace }}"
+          export CLUSTER_ID=${{ steps.bootstrap_cluster.outputs.cluster_id }}
+          export CLUSTER_SECRET=${{ steps.bootstrap_cluster.outputs.cluster_secret }}
+          export CLUSTER_IP=${{ steps.bootstrap_cluster.outputs.cluster_ip }}
+          export API_BASE_URL=${{ steps.bootstrap_cluster.outputs.cluster_api_gateway_endpoint }}
+          export BASTION_SERVER=${{ steps.terraform_outputs.outputs.bastion_public_ip }}
+          export KEY_NAME=${{ steps.terraform_outputs.outputs.key_name }}
+          export AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}
+          export AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}
+          export AWS_REGION=${{ secrets.AWS_REGION }}
+          export SBCLI_CMD=${{ github.event.inputs.sbcli_cmd || 'sbcli-dev' }}
           TESTNAME=""
           if [ -n "${{ github.event.inputs.testname }}" ]; then
             TESTNAME="--testname ${{ github.event.inputs.testname }}"
@@ -159,6 +182,83 @@ jobs:
           echo "TEST_TIME_HOURS=$TEST_TIME_HOURS" >> $GITHUB_ENV
           echo "TEST_TIME_MINS=$TEST_TIME_MINS" >> $GITHUB_ENV
           echo "TEST_TIME_SECS=$TEST_TIME_SECS" >> $GITHUB_ENV
+
+      - name: Upload automation and docker logs to s3
+        run: |
+          cd $GITHUB_WORKSPACE/e2e/logs
+          ./upload_logs.sh
+          cd $GITHUB_WORKSPACE/simplyBlockDeploy
+          ./upload_docker_logs_to_s3.sh
+        if: always()
+        env:
+          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
+          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
+          AWS_REGION: ${{ secrets.AWS_REGION }}
+          S3_BUCKET_NAME: "simplyblock-e2e-test-logs"
+          RUN_ID: ${{ github.run_id }}
+
+      - name: Parse test results
+        if: always() && github.event.inputs.send_slack_notification == 'true'
+        id: parse_results
+        run: |
+          cd $GITHUB_WORKSPACE/e2e/logs
+          echo "Looking for the latest non-empty log file..."
+          # Find the latest non-empty log file
+          COUNTER=0
+          MAX_ATTEMPTS=10
+          while [ $COUNTER -lt $MAX_ATTEMPTS ]; do
+            LATEST_LOG=$(ls -t *.log | head -n 1)
+            if [ -s "$LATEST_LOG" ]; then
+              echo "Found non-empty log file: $LATEST_LOG"
+              break
+            fi
+            echo "Attempt $((COUNTER + 1)): No non-empty log file found. Retrying..."
+            COUNTER=$((COUNTER + 1))
+            sleep 1  # Add a small delay to avoid rapid looping
+          done
+          if [ ! -s "$LATEST_LOG" ]; then
+            echo "No non-empty log file found after $MAX_ATTEMPTS attempts"
+            exit 1
+          fi
+          echo "Parsing the identified log file: $LATEST_LOG"
+          # Parse the identified log file
+          echo "Total tests"
+          TOTAL_TESTS=$(grep -i "Number of Total Cases" "$LATEST_LOG" | awk '{print $NF}')
+          echo "number Passed tests"
+          PASSED_TESTS=$(grep -i "Number of Passed Cases" "$LATEST_LOG" | awk '{print $NF}')
+          echo "number Failed tests"
+          FAILED_TESTS=$(grep -i "Number of Failed Cases" "$LATEST_LOG" | awk '{print $NF}')
+          echo "List Passed tests"
+          PASSED_CASES=$(grep "PASSED CASE" "$LATEST_LOG" | awk -F 'INFO - | FAILED CASE' '{print $2}')
+          echo "List Failed tests"
+          FAILED_CASES=$(grep "FAILED CASE" "$LATEST_LOG" | awk -F 'INFO - | FAILED CASE' '{print $2}')
+          # Format passed and failed cases as bullet points
+          echo "Adding PASSED cases with bullets: $PASSED_CASES"
+          echo "Adding FAILED cases with bullets: $PASSED_CASES"
+          PASSED_CASES_BULLETS=$(echo "$PASSED_CASES" | awk '{printf "    • %s\n", $0}')
+          FAILED_CASES_BULLETS=$(echo "$FAILED_CASES" | awk '{printf "    • %s\n", $0}')
+          echo "PASSED cases with bullets: $PASSED_CASES_BULLETS"
+          echo "FAILED cases with bullets: $FAILED_CASES_BULLETS"
+          echo "TOTAL_TESTS=${TOTAL_TESTS}"
+          echo "PASSED_TESTS=${PASSED_TESTS}"
+          echo "FAILED_TESTS=${FAILED_TESTS}"
+          echo "PASSED_CASES=${PASSED_CASES}"
+          echo "FAILED_CASES=${FAILED_CASES}"
+          echo "PASSED_TESTS=${PASSED_TESTS}" >> $GITHUB_ENV
+          echo "FAILED_TESTS=${FAILED_TESTS}" >> $GITHUB_ENV
+          echo "TOTAL_TESTS=${TOTAL_TESTS}" >> $GITHUB_ENV
+          echo "PASSED_CASES<<EOF" >> $GITHUB_ENV
+          echo "${PASSED_CASES}" >> $GITHUB_ENV
+          echo "EOF" >> $GITHUB_ENV
+          echo "FAILED_CASES<<EOF" >> $GITHUB_ENV
+          echo "${FAILED_CASES}" >> $GITHUB_ENV
+          echo "EOF" >> $GITHUB_ENV
+          echo "PASSED_CASES_BULLETS<<EOF" >> $GITHUB_ENV
+          echo "${PASSED_CASES_BULLETS}" >> $GITHUB_ENV
+          echo "EOF" >> $GITHUB_ENV
+          echo "FAILED_CASES_BULLETS<<EOF" >> $GITHUB_ENV
+          echo "${FAILED_CASES_BULLETS}" >> $GITHUB_ENV
+          echo "EOF" >> $GITHUB_ENV
 
       - name: Send Slack Notification
         if: always() && (github.event.inputs.send_slack_notification == 'true')
